### ISSUE TITLE
Request for Pre-trained TGM Model Weights

### ISSUE THREAD

**Issue by Xjg-0216** [arplaboratory/STHN#11]
Hi，
Thank you for providing the official repository for STHN. Your work has been instrumental in advancing research in this field!
We noticed in your paper and related works that the **Boson-nighttime dataset** was extended with **additional unpaired satellite images** and **thermal images generated using TGM**. These thermal images have significantly enhanced the dataset's utility.

We would like to kindly **request the pre-trained weights for the TGM model**. Having access to these weights would greatly benefit our research by enabling us to replicate your results more effectively and explore further applications of your methodology.

Thank you for considering our request. We look forward to your response and truly appreciate your contributions to the community.

**Comment by xjh19971** [comment]
Thank you for your interest! I have uploaded the TGM models to Google Drive. Please let me know if you have any further questions.

**Comment by Xjg-0216** [comment]
Thank you very much for providing the TGM models so promptly!  I’m also looking forward to any future updates or releases related to this work. Thanks again for your help and for sharing your amazing work with the community!
